### ISSUE TITLE
Impressum trotz Robots-TXT auf Google

### ISSUE THREAD

**Issue by DarkIntaqt** [l3nnartt/lennartloesche.de#2]
![Bildschirmfoto 2021-10-24 um 12 01 10](https://user-images.githubusercontent.com/61588850/138589254-698f59bb-884f-477d-ac20-225b1639de9d.png)

Die robots.txt Datei funktioniert eigentlich nur "richtig" für Bilder, deshalb erscheinen bei html Dateien meist leere Seiten in den Suchergebnissen. Deshalb ist es wichtig, bei html Dateien immer einen noindex Tag im <head> zu haben. 
```html
<meta name="robots" content="noindex">
```

**Comment by l3nnartt** [comment]
Die Seite sollte nicht indexiert sein.
![image](https://user-images.githubusercontent.com/69513317/138589645-46cf64f1-d161-48a0-9ce9-7c8534127d6d.png)

![image](https://user-images.githubusercontent.com/69513317/138589684-da2871e5-0d0a-43ff-bf77-ee3e1fa0e2f7.png)

**Comment by DarkIntaqt** [comment]
Drück mal auf "Suche unter Einbeziehung der übersprungenen Ergebnisse wiederholen. "

Google verhält sich bei der Robots.txt Datei etwas komisch mit html Dateien, wollte lediglich darauf hinweisen. 

Über die Search Console kann man die Links natürlich richtig entfernen, das geht auch!

**Comment by l3nnartt** [comment]
Ah I see, danke!
Ich pass es die Tage mal an :D
